# Generated by Django 2.2.14 on 2021-02-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
